### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by scotthovestadt** [bcoe/hl#5]
`Failed at the oniguruma@5.1.2 install script 'node-gyp rebuild'.`

Probably not compatible with newest version of NodeJS?

**Comment by jonathanmarvens** [comment]
@scotthovestadt Yes, that's the issue. If you run `npm i -g hl` with **Node.js** v0.12.7, you should be fine. I use [n](https://github.com/tj/n) to switch between different **Node.js** versions. I recommend it if you're not already familiar with it. This is, of course, still an issue though.

![screenshot 2015-10-26 21 40 07](https://cloud.githubusercontent.com/assets/890200/10747332/408cdf2a-7c2a-11e5-9639-a17fe61569f1.jpg)

CC: @bcoe, @aredridel.

**Comment by aredridel** [comment]
What actually failed there, @scotthovestadt?

**Comment by jonathanmarvens** [comment]
@aredridel If you try to install `hl` with one of the latest **Node.js** versions, the installation fails as shown in the screenshot below 😕.

![screenshot 2015-10-26 21 53 47](https://cloud.githubusercontent.com/assets/890200/10747498/3cabac4a-7c2c-11e5-9437-beeffe1e1477.jpg)

**Comment by aredridel** [comment]
Update npm. Looks like `node-gyp` failing to find parts.

**Comment by bcoe** [comment]
I've been severely nerd-sniped by this issue, behold:

https://github.com/bcoe/onigurumajs

I'm going to work on making `node-gyp` an optional part of this library.

**Comment by bcoe** [comment]
`hl@1.2.0` is out, `node-gyp` should now be optional -- you get better highlighting with it since I haven't fully ported oniguruma yet.
